apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
      - name: nodeweb-container
        image: {{ .Values.image }}
        ports:
          - containerPort: 5000
      imagePullSecrets: 
      - name: hello-world-cd
